name: simple_auth_generator
description: simple_auth is an http client generator using source_gen and inspired from retrofit and chopper
version: 2.0.10
homepage: https://github.com/clancey/simple_auth

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  simple_auth: ^2.0.10
  analyzer: ^3.0.0
  build: ^2.0.0
  build_config: ^1.0.0
  path: ^1.8.0
  source_gen: ^1.0.0
  logging: ^1.0.1
  code_builder: ^4.0.0
  dart_style: ^2.0.1
dev_dependencies:
  test:
  build_runner: ^2.0.3
  build_runner_core: ^7.0.0
  build_test: ^2.1.0
  build_verify: ^2.0.0

dev_dependency_overrides:
  simple_auth:
    path: ../simple_auth