name: simple_auth_generator
description: simple_auth is an http client generator using source_gen and inspired from retrofit and chopper
version: 0.0.2
homepage: https://github.com/clancey/simple_auth
author: James Clancey <james.clancey@gmail.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  simple_auth: ^0.0.1
  analyzer: ^0.31.2-alpha.2
  build: '>=0.9.0 <0.13.0'
  build_config: ^0.2.6
  logging: ^0.11.0 
  meta: ^1.1.0
  path: ^1.3.2
  source_gen: '>=0.8.1 <0.9.0'
  code_builder: ^3.0.0
  dart_style: ^1.0.10
dev_dependencies:
  test: ^0.12.0